### ISSUE TITLE
NULL pointer error on line 418

### ISSUE THREAD

**Issue by jcaspes** [sinipelto/dayz-scripts#3]
https://github.com/sinipelto/dayz-scripts/blob/ddeadc26606bc3a95d6f958d1b1c80ff33f9c497/init.c#L417

Hello, i've a lot of NULL pointer errors line 418 after using godmod and logoff from server
I think that the code should be modified, you are testing if (!player) on line 417 but doing player.GetUID() on line 418...
I suggest to do a first if(!player) { return; }

**Comment by sinipelto** [comment]
Hi, and thanks for the excellent finding! I have now made fixes to the god mode system, but did not yet have time to test them through if it works better now..

**Comment by jcaspes** [comment]
Thank you !
